# Generated by Django 5.1.5 on 2025-01-22 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MyBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=500)),
                ('blog_desc_1', models.TextField()),
                ('blog_heading_1', models.CharField(blank=True, max_length=500, null=True)),
                ('blog_desc_2', models.TextField(blank=True, null=True)),
                ('blog_heading_2', models.CharField(blank=True, max_length=500, null=True)),
                ('blog_desc_3', models.TextField(blank=True, null=True)),
                ('blog_heading_3', models.CharField(blank=True, max_length=500, null=True)),
                ('blog_desc_4', models.TextField(blank=True, null=True)),
                ('blog_heading_4', models.CharField(blank=True, max_length=500, null=True)),
                ('blog_desc_5', models.TextField(blank=True, null=True)),
                ('blog_conclusion_h', models.CharField(blank=True, max_length=500, null=True)),
                ('blog_desc_conc', models.TextField(blank=True, null=True)),
                ('img_1', models.ImageField(upload_to='blog/')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('blog_post_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('features', models.TextField(blank=True, help_text='Enter each feature on a new line.', null=True)),
                ('specifications', models.TextField(blank=True, help_text='Enter each specification on a new line.', null=True)),
                ('box_contain', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('gst_percentage', models.FloatField(choices=[(5.0, '5%'), (12.0, '12%'), (18.0, '18%')], default=18.0)),
                ('hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('img', models.ImageField(upload_to='images/')),
                ('product_catelog', models.FileField(blank=True, null=True, upload_to='catelogs/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
    ]
