# Generated by Django 5.1.5 on 2025-02-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='blog_post_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
