# Generated by Django 5.1.5 on 2025-02-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
