# Generated by Django 5.1.5 on 2025-02-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='box_contain',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gst_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hsn_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.TextField(help_text='Enter each feature on a new line.', null=True),
        ),
    ]
