# Generated by Django 5.1.5 on 2025-02-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_product_box_contain_remove_product_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_no',
            field=models.CharField(default='', max_length=100),
        ),
    ]
