# Generated by Django 5.1.5 on 2025-02-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_model_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=300)),
                ('event_date', models.DateField(auto_now_add=True)),
                ('event_img', models.ImageField(upload_to='events/')),
            ],
        ),
    ]
