# Generated by Django 5.1.5 on 2025-05-13 10:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='product-images/'),
        ),
    ]
