# Generated by Django 5.1.5 on 2025-05-13 11:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_catelog',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product-catalogue/'),
        ),
    ]
