# Generated by Django 5.1.5 on 2025-05-14 09:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_product_product_catelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='events/'),
        ),
        migrations.AlterField(
            model_name='myblog',
            name='img_1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='blog-images/'),
        ),
        migrations.AlterField(
            model_name='myblog',
            name='img_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='blog-images/'),
        ),
    ]
